### ISSUE TITLE
Network protocol error 

### ISSUE THREAD

**Issue by Xelaa-Dev** [fantomitechno/Emotes#6] opened 2024-08-05 07:17 UTC
:(
```
Description: Packet handling error

java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because the return value of "dev.renoux.emotes.util.EmoteUtil.getCodepoint(String)" is null
	at net.minecraft.class_2588.redirect$zzb000$emotes$visit(class_2588.java:553)
	at net.minecraft.class_2588.method_27660(class_2588.java:185)
	at net.minecraft.class_2561.method_27658(class_2561.java:97)
	at net.minecraft.class_341.method_1850(class_341.java:25)
	at net.minecraft.class_338.method_1815(class_338.java:236)
	at net.minecraft.class_338.method_44811(class_338.java:214)
	at net.minecraft.class_338.method_1812(class_338.java:208)
	at net.minecraft.class_7594.method_45745(class_7594.java:125)
	at net.minecraft.class_7594.method_44818(class_7594.java:88)
	at net.minecraft.class_7594.method_45746(class_7594.java:123)
	at net.minecraft.class_634.method_45724(class_634.java:947)
	at net.minecraft.class_7827.method_46324(class_7827.java:25)
	at net.minecraft.class_7827.method_11054(class_7827.java:11)
	at net.minecraft.class_2600.method_11072(class_2600.java:27)
	at net.minecraft.class_1255.method_18859(class_1255.java:162)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.class_1255.method_16075(class_1255.java:136)
	at net.minecraft.class_1255.method_5383(class_1255.java:121)
	at net.minecraft.class_310.method_1523(class_310.java:1240)
	at net.minecraft.class_310.method_1514(class_310.java:882)
	at net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_2588.redirect$zzb000$emotes$visit(class_2588.java:553)
	at net.minecraft.class_2588.method_27660(class_2588.java:185)
	at net.minecraft.class_2561.method_27658(class_2561.java:97)
	at net.minecraft.class_341.method_1850(class_341.java:25)
	at net.minecraft.class_338.method_1815(class_338.java:236)
	at net.minecraft.class_338.method_44811(class_338.java:214)
	at net.minecraft.class_338.method_1812(class_338.java:208)
	at net.minecraft.class_7594.method_45745(class_7594.java:125)
	at net.minecraft.class_7594.method_44818(class_7594.java:88)
	at net.minecraft.class_7594.method_45746(class_7594.java:123)

-- Incoming Packet --
Details:
	Type: clientbound/minecraft:disguised_chat
	Is Terminal: false
	Is Skippable: true
Stacktrace:
	at net.minecraft.class_2600.method_59803(class_2600.java:56)
	at net.minecraft.class_8673.method_60882(class_8673.java:136)
	at net.minecraft.class_8673.method_59807(class_8673.java:113)
	at net.minecraft.class_2600.method_11072(class_2600.java:32)
	at net.minecraft.class_1255.method_18859(class_1255.java:162)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.class_1255.method_16075(class_1255.java:136)
	at net.minecraft.class_1255.method_5383(class_1255.java:121)
	at net.minecraft.class_310.method_1523(class_310.java:1240)
	at net.minecraft.class_310.method_1514(class_310.java:882)
	at net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Connection --
Details:
	Protocol: play
	Flow: CLIENTBOUND
	Server type: OTHER
	Server brand: fabric

-- System Details --
Details:
	Minecraft Version: 1.21
	Minecraft Version ID: 1.21
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 21.0.3, Azul Systems, Inc.
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Azul Systems, Inc.
	Memory: 223270104 bytes (212 MiB) / 622854144 bytes (594 MiB) up to 4160749568 bytes (3968 MiB)
	CPUs: 12
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 3600X 6-Core Processor             
	Identifier: AuthenticAMD Family 23 Model 113 Stepping 0
	Microarchitecture: Zen 2
	Frequency (GHz): 3.80
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: NVIDIA GeForce GTX 1660 SUPER
	Graphics card #0 vendor: NVIDIA
	Graphics card #0 VRAM (MiB): 6144.00
	Graphics card #0 deviceId: VideoController1
	Graphics card #0 versionInfo: 32.0.15.5599
	Memory slot #0 capacity (MiB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.13
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MiB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.13
	Memory slot #1 type: DDR4
	Memory slot #2 capacity (MiB): 8192.00
	Memory slot #2 clockSpeed (GHz): 2.13
	Memory slot #2 type: DDR4
	Memory slot #3 capacity (MiB): 8192.00
	Memory slot #3 clockSpeed (GHz): 2.13
	Memory slot #3 type: DDR4
	Virtual memory max (MiB): 34767.91
	Virtual memory used (MiB): 15954.11
	Swap memory total (MiB): 2048.00
	Swap memory used (MiB): 233.31
	Space in storage for jna.tmpdir (MiB): available: 164093.22, total: 953114.00
	Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): available: 164093.22, total: 953114.00
	Space in storage for io.netty.native.workdir (MiB): available: 164093.22, total: 953114.00
	Space in storage for java.io.tmpdir (MiB): available: 164093.22, total: 953114.00
	Space in storage for workdir (MiB): available: 164093.22, total: 953114.00
	JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3968M
	Fabric Mods: 
		emotes: Emotes Mod Client 1.1.3
			com_electronwill_night-config_core: core 3.6.6
			com_electronwill_night-config_toml: toml 3.6.6
			org_quiltmc_quilt-config: quilt-config 1.3.1
			org_quiltmc_quilt-config_serializers_toml: toml 1.3.1
		fabric-api: Fabric API 0.101.1+1.21
			fabric-api-base: Fabric API Base 0.4.42+6573ed8cd1
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.68+b5597344d1
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.29+5bd9f1bcd1
			fabric-block-api-v1: Fabric Block API (v1) 1.0.22+0af3f5a7d1
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.10+6573ed8cd1
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.52+0af3f5a7d1
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.15+6573ed8cd1
			fabric-command-api-v1: Fabric Command API (v1) 1.2.49+f71b366fd1
			fabric-command-api-v2: Fabric Command API (v2) 2.2.28+6ced4dd9d1
			fabric-commands-v0: Fabric Commands (v0) 0.2.66+df3654b3d1
			fabric-content-registries-v0: Fabric Content Registries (v0) 8.0.16+b5597344d1
			fabric-convention-tags-v1: Fabric Convention Tags 2.0.19+7f945d5bd1
			fabric-convention-tags-v2: Fabric Convention Tags (v2) 2.5.0+c5e2b5c6d1
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.29+0af3f5a7d1
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.1.26+6a6dfa19d1
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 20.2.15+16c4ae25d1
			fabric-dimensions-v1: Fabric Dimensions API (v1) 4.0.0+6fc22b99d1
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.12+6fc22b99d1
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.11+ba9dae06d1
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.53+6ced4dd9d1
			fabric-item-api-v1: Fabric Item API (v1) 11.0.0+afdfc921d1
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.1.4+78017270d1
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.47+0af3f5a7d1
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.45+df3654b3d1
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.3.12+6c1df360d1
			fabric-loot-api-v2: Fabric Loot API (v2) 3.0.14+3f89f5a5d1
			fabric-loot-api-v3: Fabric Loot API (v3) 1.0.2+3f89f5a5d1
			fabric-message-api-v1: Fabric Message API (v1) 6.0.13+6573ed8cd1
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 2.0.0+fe474d6bd1
			fabric-networking-api-v1: Fabric Networking API (v1) 4.2.1+8759e755d1
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 15.1.14+d1321076d1
			fabric-particles-v1: Fabric Particles (v1) 4.0.2+6573ed8cd1
			fabric-recipe-api-v1: Fabric Recipe API (v1) 5.0.11+65089712d1
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 5.1.1+0a3a0057d1
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.4.0+c705a49cd1
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.7.0+c705a49cd1
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.68+df3654b3d1
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.48+73761d2ed1
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.6+b5597344d1
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.71+df3654b3d1
			fabric-rendering-v1: Fabric Rendering (v1) 5.0.5+df16efd0d1
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 4.3.0+8dc279b1d1
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 1.3.0+56599129d1
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.24+b5597344d1
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.85+b5597344d1
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.23+6573ed8cd1
			fabric-transfer-api-v1: Fabric Transfer API (v1) 5.1.16+3dccd343d1
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 6.1.0+176f9036d1
		fabricloader: Fabric Loader 0.15.11
			mixinextras: MixinExtras 0.3.5
		java: OpenJDK 64-Bit Server VM 21
		minecraft: Minecraft 1.21
		modmenu: Mod Menu 11.0.1
			placeholder-api: Placeholder API 2.4.0-pre.2+1.21
```

**Comment by fantomitechno** [comment] 2024-08-05 07:26
probably duplicate of #2 

if it's not that gives me more information

**Comment by Xelaa-Dev** [comment] 2024-08-05 07:35
this time it's not the image bc I made it a square so idk anymore lol

**Comment by fantomitechno** [comment] 2024-08-05 08:57
Can you give me your config and the emote(s) file(s)?

**Comment by Xelaa-Dev** [comment] 2024-08-05 09:27
![image](https://github.com/user-attachments/assets/7abb94a7-cf31-4cee-9cb6-0c529aaf7e23)

![kappa (1)](https://github.com/user-attachments/assets/aeb44aa8-aae2-494f-b12b-75ea44651f09)

**Comment by Xelaa-Dev** [comment] 2024-08-05 09:27
its stretched bc of 400x400

**Comment by fantomitechno** [comment] 2024-08-05 09:29
And how do you get the error, what did you do?

**Comment by Xelaa-Dev** [comment] 2024-08-05 10:20
typed :kappa: in chat and as soon as i hit enter it disconnects me

**Comment by Xelaa-Dev** [comment] 2024-08-05 10:20
also idk if its of relevance buyt the autocomplete doesnt show up

**Comment by Xelaa-Dev** [comment] 2024-08-05 10:20
oh and the server runs on linux

**Comment by fantomitechno** [comment] 2024-08-05 10:59
I can't reproduce: I crash directly with the same things as yesterday, does your client use the right version of the mod, same for the server

**Comment by Xelaa-Dev** [comment] 2024-08-05 11:00
same versions on client and server yes

**Comment by fantomitechno** [comment] 2024-08-05 11:12
https://github.com/user-attachments/assets/a7340482-de05-4be1-a06b-265482612d86

**Comment by Xelaa-Dev** [comment] 2024-08-05 11:16
![image](https://github.com/user-attachments/assets/d4a07acd-6524-4616-b330-2027d2120c39)
the configs fine tho i guess its the image again??

**Comment by fantomitechno** [comment] 2024-08-05 11:19
but we don't have the same error tho we have the same setup

**Comment by Xelaa-Dev** [comment] 2024-08-05 11:20
im gonna double check everything

**Comment by fantomitechno** [comment] 2024-08-05 11:20
try with an other image

**Comment by fantomitechno** [comment] 2024-08-05 11:20
anything else square

**Comment by Xelaa-Dev** [comment] 2024-08-05 11:22
same problem with different image

**Comment by fantomitechno** [comment] 2024-08-05 11:23
record video of the bug

**Comment by Xelaa-Dev** [comment] 2024-08-05 11:25
https://github.com/user-attachments/assets/9c292308-669c-4245-be5d-48df5b4dc362

**Comment by Xelaa-Dev** [comment] 2024-08-05 11:25
so sorry if im wasting ur time

**Comment by fantomitechno** [comment] 2024-08-05 11:36
On your client, could you find the folder `config/emotes/cache/<ip of server>` and show me its content?

**Comment by Xelaa-Dev** [comment] 2024-08-05 13:42
> On your client, could you find the folder `config/emotes/cache/<ip of server>` and show me its content?

![image](https://github.com/user-attachments/assets/c275febb-5e65-4ee9-a67d-fe02630baf69)
its just the emoji

**Comment by Xelaa-Dev** [comment] 2024-08-05 13:46
tho i did notice the config on the client had the broken emote line like this 
![image](https://github.com/user-attachments/assets/297537b8-2cb7-404a-8b87-c01b0b0ff654)ù
i tried to set it to just one but no difference

**Comment by fantomitechno** [comment] 2024-08-05 14:10
The config isn't read and used by the client

**Comment by Xelaa-Dev** [comment] 2024-08-05 14:15
ah fair

**Comment by Xelaa-Dev** [comment] 2024-08-05 14:47
wait does the plugin excpect a port in particular to send stuff through? (idk if all communications are binded to the server port)

**Comment by fantomitechno** [comment] 2024-08-05 16:02
> wait does the plugin excpect a port in particular to send stuff through? (idk if all communications are binded to the server port)

No it uses the same protocol as minecraft

**Comment by fantomitechno** [comment] 2024-08-05 16:03
> > On your client, could you find the folder `config/emotes/cache/<ip of server>` and show me its content?
> 
> ![image](https://private-user-images.githubusercontent.com/78649142/355125067-c275febb-5e65-4ee9-a67d-fe02630baf69.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4NzQwMDEsIm5iZiI6MTcyMjg3MzcwMSwicGF0aCI6Ii83ODY0OTE0Mi8zNTUxMjUwNjctYzI3NWZlYmItNWU2NS00ZWU5LWE2N2QtZmUwMjYzMGJhZjY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA1VDE2MDE0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFiNDE4YmVlZGUxMzE0M2NmMWNlOTFjZjVmM2U1M2M5ODFjNjk2OWMzYmM3NmJhZGFiZmI4MTlhYzZkZGYyZmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yA6JMten6YX6D2u99RXdHPqMCdEfgtn4s0n98QX-Cik) its just the emoji

uh, you should have the 2 emotes, you have on your server

**Comment by Xelaa-Dev** [comment] 2024-08-05 16:14
> > > On your client, could you find the folder `config/emotes/cache/<ip of server>` and show me its content?
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/78649142/355125067-c275febb-5e65-4ee9-a67d-fe02630baf69.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4NzQwMDEsIm5iZiI6MTcyMjg3MzcwMSwicGF0aCI6Ii83ODY0OTE0Mi8zNTUxMjUwNjctYzI3NWZlYmItNWU2NS00ZWU5LWE2N2QtZmUwMjYzMGJhZjY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA1VDE2MDE0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFiNDE4YmVlZGUxMzE0M2NmMWNlOTFjZjVmM2U1M2M5ODFjNjk2OWMzYmM3NmJhZGFiZmI4MTlhYzZkZGYyZmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yA6JMten6YX6D2u99RXdHPqMCdEfgtn4s0n98QX-Cik) its just the emoji
> 
> uh, you should have the 2 emotes, you have on your server

i mean i only have one rn for testing

**Comment by fantomitechno** [comment] 2024-08-05 16:56
I can't reproduce at all your problems :/

**Closed as completed** 2024-08-05 16:57 UTC
Labels: bug

**Comment by Xelaa-Dev** [comment] 2024-08-06 07:32
not gonna reopen it but at this point i think its something clientside bc i tried 2 different scenarios with different results

1. cleared cache makes the client hard crash
2. when the cache is actually filled with whatever emotes the server has, typing any of the emotes makes the protocol error pops up

**Comment by Xelaa-Dev** [comment] 2024-08-06 07:45
also for some reason the preview is broken and doesnt show

**Comment by fantomitechno** [comment] 2025-04-21 20:10
I've got huge news!!!!

While updating to 1.21.5, I encountered the issue and was finally able to fix it! (normally, please)
