### ISSUE TITLE
EmojiSuggestionHelper crashes the client 

### ISSUE THREAD

**Issue by Xelaa-Dev** [fantomitechno/Emotes#3] opened 2024-08-02 13:34 UTC
MInecraft version 1.21 Fbric loader version 0.100.8

```
[15:32:26] [Render thread/ERROR]:
 Reported exception thrown!
net.minecraft.class_148: Rendering screen
	at net.minecraft.class_757.method_3192(class_757.java:922) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1285) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:882) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:256) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.15.11.jar:?]
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_382.method_24045(net.minecraft.class_327$class_6415)" because "$$5" is null
	at net.minecraft.class_327$class_5232.accept(class_327.java:231) ~[client-intermediary.jar:?]
	at net.minecraft.class_5223.method_27477(class_5223.java:17) ~[client-intermediary.jar:?]
	at net.minecraft.class_5223.method_27474(class_5223.java:43) ~[client-intermediary.jar:?]
	at net.minecraft.class_5481.method_30753(class_5481.java:23) ~[client-intermediary.jar:?]
	at net.minecraft.class_327.method_27530(class_327.java:298) ~[client-intermediary.jar:?]
	at net.minecraft.class_327.method_1723(class_327.java:151) ~[client-intermediary.jar:?]
	at net.minecraft.class_327.method_22942(class_327.java:84) ~[client-intermediary.jar:?]
	at net.minecraft.class_332.method_51430(class_332.java:290) ~[client-intermediary.jar:?]
	at net.minecraft.class_332.method_51439(class_332.java:300) ~[client-intermediary.jar:?]
	at dev.renoux.emotes.util.EmojiSuggestionHelper$EmojiSuggestions.render(EmojiSuggestionHelper.java:184) ~[emotes-1.21-1.1.2.jar:?]
	at dev.renoux.emotes.util.EmojiSuggestionHelper.render(EmojiSuggestionHelper.java:149) ~[emotes-1.21-1.1.2.jar:?]
	at net.minecraft.class_408.handler$zzm000$emotes$render(class_408.java:535) ~[client-intermediary.jar:?]
	at net.minecraft.class_408.method_25394(class_408.java) ~[client-intermediary.jar:?]
	at net.minecraft.class_437.method_47413(class_437.java:117) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.mixinextras$bridge$method_47413$234(class_757.java) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.wrapOperation$zne000$fabric-screen-api-v1$onRenderScreen(class_757.java:2086) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:913) ~[client-intermediary.jar:?]
	... 6 more
```
(server stays up btw)

**Comment by fantomitechno** [comment] 2024-08-02 13:39
Thanks for the report, I will look into that!

**Comment by Xelaa-Dev** [comment] 2024-08-02 14:17
btw is something like this possible?

```
public void render(GuiGraphics matrixStack) {
        if (this.suggestions != null && **ModConfig.INSTANCE.show_suggestions**) {
            this.suggestions.render(matrixStack);
        }
        checkTextUpdate();
    }
```

**Comment by fantomitechno** [comment] 2024-08-02 14:51
it's an interesting idea, could you create a separate issue so it's not lost when I close this issue?

**Comment by fantomitechno** [comment] 2024-08-04 12:45
@xela-the-proto when does this happen, I can't reproduce :/

**Comment by WilcoM** [comment] 2024-08-04 14:32
> @xela-the-proto when does this happen, I can't reproduce :/

Happened to me when I type : in chat on client

**Comment by fantomitechno** [comment] 2024-08-04 14:36
I have a fresh instance on a server with emotes without using the new config I added\
No other mods on the client and the server


https://github.com/user-attachments/assets/ed3dd845-b415-4cee-bc8a-7a74868c13e1

**Comment by Xelaa-Dev** [comment] 2024-08-04 16:40
tried it too at this point idk if its my pc or what

https://github.com/user-attachments/assets/d2da5e82-fb3e-4ffb-a2e1-9286b09ffa43

**Comment by fantomitechno** [comment] 2024-08-04 16:41
You have two time the same emote in your config!

**Comment by Xelaa-Dev** [comment] 2024-08-04 16:42
> You have two time the same emote in your config!

if its why ive been having problems ill be so mad

**Comment by Xelaa-Dev** [comment] 2024-08-04 16:43
nope same crash

**Comment by Xelaa-Dev** [comment] 2024-08-04 16:46
if i do :kappa: without the mod on the client it works fine and displayes the alternate text

**Comment by fantomitechno** [comment] 2024-08-04 16:46
Can you send me your emote? maybe it's the image

**Comment by Xelaa-Dev** [comment] 2024-08-04 16:46
![kappa](https://github.com/user-attachments/assets/e9fb6f2d-f257-4bfc-ba42-35d501b46d13)

**Comment by fantomitechno** [comment] 2024-08-04 16:49
OK we have it

**Comment by fantomitechno** [comment] 2024-08-04 16:49
it's the image

**Comment by fantomitechno** [comment] 2024-08-04 16:49
I'm gonna try to figure out why this one does and do my best for every image to work but already I have an idea of what cause the crash finaly

**Comment by Xelaa-Dev** [comment] 2024-08-04 16:50
> it's the image

💀 shouldve known it srry for wasting ur time lol

**Comment by fantomitechno** [comment] 2024-08-04 16:51
No, no I need problems like that so every image works!

**Comment by Xelaa-Dev** [comment] 2024-08-04 16:51
fair enough imam close the issue if its ok with u

**Comment by fantomitechno** [comment] 2024-08-04 16:52
no don't! I want to make errors and stuff for images that crash so I need to understand why this one is a probem

**Comment by Xelaa-Dev** [comment] 2024-08-04 16:52
kk

**Comment by fantomitechno** [comment] 2024-08-04 16:52
The image I received is rectangle, is it the case on your side too?

**Comment by Xelaa-Dev** [comment] 2024-08-04 17:23
![image](https://github.com/user-attachments/assets/9c787cae-7afa-4e53-826b-2a7616c2cfbf)
yea it is

**Comment by fantomitechno** [comment] 2024-08-04 17:35
Okay, that may explain, for now only square image is supported, but I want to update for emotes like FFZ/7TV on Twitch

**Comment by fantomitechno** [comment] 2024-08-04 17:36
@WilcoM can you confirm that it's the same problem? (aka format)

**Comment by WilcoM** [comment] 2024-08-04 20:31
That seems to be it!

**Comment by fantomitechno** [comment] 2024-08-04 20:33
Okay, I'm gonna make the mod description clearer on that point!
but so you know, my plan would be to remove this limitation to be able to have rectangular emotes but it's not easy in a block game 😓

**Closed as completed by fantomitechno** 2024-08-04 20:33 UTC
Labels: bug

**Comment by Xelaa-Dev** [comment] 2024-08-05 04:57
just a thought u could just resive down to the nearest square with some Java library like if the image is 1280 x 720 you get the lower number and resize to that (first thing that came to mind so it's prolly wrong)
